// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed_follow.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one
with inserted_feed_follow as (
    INSERT INTO feed_follows(id,created_at,updated_at,user_id,feed_id) Values ($1,$2,$3,$4,$5)
    returning id, created_at, updated_at, user_id, feed_id
) SELECT 
    iff.id, iff.created_at, iff.updated_at, iff.user_id, iff.feed_id,
    f.name as feed,
    u.name as username
    from inserted_feed_follow as iff
    inner join feeds as f
    on iff.feed_id = f.id
    inner join users as u
    on iff.user_id = u.id
`

type CreateFeedFollowParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

type CreateFeedFollowRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
	Feed      string
	Username  string
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (CreateFeedFollowRow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.FeedID,
	)
	var i CreateFeedFollowRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
		&i.Feed,
		&i.Username,
	)
	return i, err
}

const getFeedFollowsForUser = `-- name: GetFeedFollowsForUser :many
select u.name as username, f.name as feed
from feed_follows as ff
inner join feeds as f
on ff.feed_id = f.id
inner join users as u
on ff.user_id = u.id
where ff.user_id = $1
`

type GetFeedFollowsForUserRow struct {
	Username string
	Feed     string
}

func (q *Queries) GetFeedFollowsForUser(ctx context.Context, userID uuid.UUID) ([]GetFeedFollowsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedFollowsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedFollowsForUserRow
	for rows.Next() {
		var i GetFeedFollowsForUserRow
		if err := rows.Scan(&i.Username, &i.Feed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetFeedFollowings = `-- name: ResetFeedFollowings :exec
delete from feed_follows
`

func (q *Queries) ResetFeedFollowings(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetFeedFollowings)
	return err
}

const unfollow = `-- name: Unfollow :exec
DELETE FROM feed_follows ff
USING feeds f, users u
WHERE ff.feed_id = f.id
  AND ff.user_id = u.id
  AND f.url = $1
  AND u.name = $2
`

type UnfollowParams struct {
	Url  string
	Name string
}

func (q *Queries) Unfollow(ctx context.Context, arg UnfollowParams) error {
	_, err := q.db.ExecContext(ctx, unfollow, arg.Url, arg.Name)
	return err
}
